name: Zephyr CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y --no-install-recommends \
          git cmake ninja-build gperf \
          ccache dfu-util device-tree-compiler wget \
          python3-dev python3-pip python3-setuptools python3-tk python3-wheel xz-utils file \
          make gcc gcc-multilib g++-multilib libsdl2-dev

    - name: Set up Python Virtual Environment
      run: |
        python3 -m venv ~/zephyr-venv
        source ~/zephyr-venv/bin/activate

    - name: Install Zephyr SDK using West
      run: |
        source ~/zephyr-venv/bin/activate
        pip install west
        # If the workspace is already initialized, skip west init
        if [ ! -d "$HOME/zephyrproject/.west" ]; then
          west init ~/zephyrproject
        fi
        cd ~/zephyrproject
        west update
        west zephyr-export

        # Install Zephyr SDK and Python dependencies using West
        west packages pip --install
        west sdk install

    - name: Build Application
      run: |
        source ~/zephyr-venv/bin/activate
        cd ~/zephyrproject
        west zephyr-export
        west build -b native_sim $GITHUB_WORKSPACE

    # - name: Run Tests
    #   run: |
    #     source ~/zephyrproject/zephyr/zephyr-env.sh
    #     cd $GITHUB_WORKSPACE
    #     west build -b native_sim -- -DBUILD_TESTING=ON
    #     west build -t run
