name: Zephyr CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    container: zephyrprojectrtos/zephyr-build:v0.24.1

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y --no-install-recommends \
          git cmake ninja-build gperf \
          ccache dfu-util device-tree-compiler wget \
          python3-dev python3-pip python3-setuptools python3-tk python3-wheel xz-utils file \
          make gcc gcc-multilib g++-multilib libsdl2-dev

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'

    - name: Install Python dependencies
      run: |
        pip install west
        west init ~/zephyrproject
        cd ~/zephyrproject
        west update
        pip install -r ~/zephyrproject/zephyr/scripts/requirements.txt

    - name: Build Application
      run: |
        source ~/zephyrproject/zephyr/zephyr-env.sh
        cd $GITHUB_WORKSPACE
        west build -b native_posix_64

    - name: Run Tests
      run: |
        source ~/zephyrproject/zephyr/zephyr-env.sh
        cd $GITHUB_WORKSPACE
        west build -b native_posix_64 -- -DBUILD_TESTING=ON
        west build -t run

    - name: Upload Artifacts
      if: ${{ always() }}
      uses: actions/upload-artifact@v3
      with:
        name: build-output
        path: |
          build/zephyr/zephyr.elf
          build/zephyr/zephyr.map
          build/Testing/**/Test.xml